blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [
    # Example: /blog/
    path('', views.PostLV.as_view(), name='index'),

    # Example: /blog/post/
    path('post/', views.PostLV.as_view(), name='post_list'),

    # Example: /blog/post/django-example/ 한글도 인식 가능
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),

    # Example: /blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),

    # Example: /blog/archive/2022/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    # Example: /blog/archive/2022/jan/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    # Example: /blog/archive/2022/jan/09/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),

    # Example: /blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

    path('add/', views.PostCreateView.as_view(), name='add'),

    path('change/', views.PostChangeLV.as_view(), name='change'),

    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),

    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
    ]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views
from mysite.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('blog/', include('blog.urls')),
    path('login/', login, name='login'),
    path('login/done/', LoginDoneTV.as_view(), name='login_done'),
    path('logout/', logout, name='logout'),
    path('myPage/', MyPage.as_view(), name='myPage'),
    path('register/', signup, name='register'),
    path('register/done/', views.SearchFormView.as_view(), name='register_done'),
]

blog/models.py
from django.db import models
from django.urls import reverse
#from django.contrib.auth.models import User
from account.models import User
from django.utils.text import slugify


class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text')
    content = models.TextField('CONTENT', blank=True)
    create_dt = models.DateTimeField('CREATE DATE', auto_now_add=True)
    modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='OWNER', blank=True, null=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'blog_posts'
        ordering = ('-modify_dt',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,))

    def get_previous(self):
        return self.get_previous_by_modify_dt()

    def get_next(self):
        return self.get_next_by_modify_dt()

    def save(self, *arg, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        super().save(*arg, **kwargs)

blog/forms.py
from django import forms


class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='SearchWord')

blog/views.py
# Create your views here.
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView, TodayArchiveView
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView
from django.conf import settings

from blog.models import Post

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from mysite.views import OwnerOnlyMixin

from django.views.generic import FormView
from blog.forms import PostSearchForm
from django.db.models import Q
from django.shortcuts import render


#--- ListView
class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 5


#--- DetailView
class PostDV(DetailView):
    model = Post


#---ArchieveView
class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_dt'


class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_dt'
    make_object_list = True


class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_dt'


class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_dt'


class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_dt'


class SearchFormView(FormView):
    form_class = PostSearchForm
    template_name = 'blog/post_search.html'

    def form_valid(self, form):
        searchWord = form.cleaned_data['search_word']
        post_list1 = Post.objects.filter(Q(content__icontains=searchWord)).distinct()
        post_list_semi = Post.objects.exclude(Q(content__icontains=searchWord)).distinct()
        post_list2 = post_list_semi.filter(Q(title__icontains=searchWord)).distinct()

        context = {}
        context['form'] = form
        context['search_term'] = searchWord
        context['object_list1'] = post_list1
        context['object_list2'] = post_list2

        return render(self.request, 'blog/post_search2.html', context)


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'slug', 'description', 'content']
    initial = {'slug': 'auto-filling-do-not-input'}
    success_url = reverse_lazy('blog:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class PostChangeLV(LoginRequiredMixin, ListView):
    template_name = 'blog/post_change_list.html'

    def get_queryset(self):
        return Post.objects.filter(owner=self.request.user)


class PostUpdateView(OwnerOnlyMixin, UpdateView):
    model = Post
    fields = ['title', 'slug', 'description', 'content']


class PostDeleteView(OwnerOnlyMixin, DetailView):
    model = Post
    success_url = reverse_lazy('blog:index')

blog/templates/blog/post_all.html
{% extends "base.html" %}
{% block title %}post_all.html{% endblock %}
{% block content %}

    <h1>Blog List</h1>
    <div align="right">
        <a href="{% url 'blog:add' %}" style=""><button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" style="background-color: #0d6efd; color: #FFFFFF;">Post</button></a>
    </div>0
    <br>
    {% for post in posts %}
        <h3 align="right" style="float:right">{{ post.owner.get_username }}</h3>
        <h3><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h3>
        <p align="right" style="float:right">{{ post.modify_dt|date:"j F Y" }}</p>
        <p>{{ post.description }}</p>
    {% endfor %}

    <br>
    <div>
        <span>
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">PreviousPage</a>
            {% endif %}

            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">NextPage</a>
            {% endif %}
        </span>
    </div>

{% endblock %}

blog/templates/blog/post_archive.html
{% extends "base.html" %}
{% block title %}post_archive.html{% endblock %}
{% block content %}

    <h1>Post Archives until {% now "N d, Y" %}</h1>

        {% for date in date_list %}
        <a href="{% url 'blog:post_year_archive' date|date:'Y' %}"
            class="btn btn-outline-primary btn-sm mx-1">
            Year-{{ date|date:"Y" }}
        </a>
        {% endfor %}
    <br><br>

    <div>
        <ul>
            {% for post in object_list %}
            <li class="h5">{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

blog/templates/blog/post_archive_day.html
{% extends "base.html" %}
{% block title %}post_archive_day.html{% endblock %}
{% block content %}


    <h1>Post Archives for {{ day|date:"N d, Y" }}</h1>
    </br>
    <div>
        <ul>
            {% for post in object_list %}
            <li>{{ post.modify_dt|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
            <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

blog/templates/blog/post_archive_month.html
{% extends "base.html" %}
{% block title %}post_archive_month.html{% endblock %}
{% block content %}

    <h1>Post Archives for {{ month|date:"N, Y" }}</h1>
    <br><br>

    <div>
        <ul>
            {% for post in object_list %}
            <li class="h5">
                {{ post.modify_dt|date:"Y-m-d" }}&emsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

blog/templates/blog/post_archive_year.html
{% extends "base.html" %}
{% block title %}post_archive_year.html{% endblock %}
{% block content %}

    <h1>Post Archives for {{ year|date:"Y" }}</h1>

    {% for date in date_list %}
    <a href="{% url 'blog:post_month_archive' date|date:'Y' date|date:'b' %}"
       class="btn btn-outline-primary btn-sm mx-1">
        {{ date|date:"F" }}</a>
    {% endfor %}

    <br><br>

    <div>
        <ul>
            {% for post in object_list %}
            <li class="h5">
                {{ post.modify_dt|date:"Y-m-d" }}&emsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

blog/templates/blog/post_change_list.html
{% extends "base.html" %}
{% block title %}post_change_list.html{% endblock %}
{% block content %}

<h1>Post Change - {{user}}</h1>
<br>

<table class="table table-bordered table-condensed table-striped">
    <thead>
        <tr class="table-primary">
            <th>Title</th>
            <th>Url</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
    </thead>

    <tbody>
        {% for item in object_list %}
        <tr>
            <td>{{ item.title }}</td>
            <td>{{ item.url }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'blog:update' item.id %}">Update</a></td>
            <td><a href="{% url 'blog:delete' item.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %}
{% block title %}post_confirm_delete.html{% endblock %}
{% block content %}

<h1>Post Delete</h1>
<br>
<form action="." method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" class="btn btn-danger btn-sm"/>
</form>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends "base.html" %}
{% block title %}post_detail.html{% endblock %}

{% block extra-style %}
<style>
.post-body{
    width: 80%;
    margin: auto;
    font-family: "Lucida Grande", Verdana, Arial, sans-serif;
    font-size: 16px;
}
</style>
{% endblock extra-style %}

{% block content %}
<div class="post-body">

    <h2>{{ object.title }}</h2>

    <br>

    <div>
        {{ object.content|linebreaks }}
    </div>

</div>

<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" style="background-color: #0d6efd; color: #FFFFFF;"></button></a>

<div align="right">
    <a href="{% url 'register_done' %}" style=""><button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" style="background-color: #0d6efd; color: #FFFFFF;"></button></a>
</div>

{% endblock %}

blog/templates/blog/post_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}post_form.html{% endblock %}

{% block content %}

    <h1>Post Create - {{user}}</h1>
    <p class="font-italic">This is a creation or update form for your post.</p>
    <p class="font-italic">Since we make a key with title, so you must write a unique title.</p>

    {% if form.errors %}
    <div class="alert alert-danger">
        <div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
        {{ form.errors }}
    </div>
    {% endif %}

    <form action="." method="post" class="card pt-3">{% csrf_token %}
        <div class="form-group row">
            {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.title|add_class:"form-control"|attr:"autofocus" }}
            </div>
        </div>

        <div class="form-group row" style="display:none">
            {{ form.slug|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.slug|add_class:"form-control"|attr:"readonly" }}
            </div>
            <small class="form-text text-muted">{{ form.slug.help_text }}</small>
        </div>


        <div class="form-group">
            <div class="offset-sm-2 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-info"/>
            </div>
        </div>
    </form>

{% endblock %}

blog/templates/blog/post_search.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}post_search.html{% endblock %}

{% block content %}

    <h1>시간표 등록</h1>
    <br>

    <form action="." method="post"> {% csrf_token %}
        <div class="form-group row">
            <div style="width: 25%;">
            {{ form.search_word|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            </div>
            <div class="col-sm-3" style="float: left; width: 50%;">
                {{ form.search_word|add_class:"form-control"|attr:"autofocus" }}
            </div>
            <div style="margin:auto; float: left; width: 25%;">
                    <input type="submit" value="Submit" class="btn btn-primary btn-sm">
            </div>
        </div>
    </form>

    <br/><br/>

    {% if object_list %}
        {% for post in object_list %}
        <h2><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h2>
        {% endfor %}

    {% elif search_term %}
    <b><i>Search Word({{ search_term }}) Not Found !</i></b>
    {% endif %}

{% endblock %}

blog/templates/blog/post_search2.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}post_search.html{% endblock %}

{% block content %}

    <h1>{{search_term}}</h1>
    <br/><br/>

    {% if object_list1 %}
        {% for post in object_list1 %}
        <h2><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h2>
        {% endfor %}
    {% endif %}

    {% if object_list2 %}
        {% for post in object_list2 %}
        <h2><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h2>
        {% endfor %}
    {% endif %}

    {% if not object_list1 and not object_list2 %}
    <b><i>Search Word({{ search_term }}) Not Found !</i></b>
    {% endif %}

{% endblock %}