blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [
    # Example: /blog/
    path('', views.PostLV.as_view(), name='index'),

    # Example: /blog/post/
    path('post/', views.PostLV.as_view(), name='post_list'),

    # Example: /blog/post/django-example/ 한글도 인식 가능
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),

    # Example: /blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),

    # Example: /blog/archive/2022/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    # Example: /blog/archive/2022/jan/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    # Example: /blog/archive/2022/jan/09/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),

    # Example: /blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

    path('add/', views.PostCreateView.as_view(), name='add'),

    path('change/', views.PostChangeLV.as_view(), name='change'),

    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),

    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
    ]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views
from mysite.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('blog/', include('blog.urls')),
    path('login/', login, name='login'),
    path('login/done/', LoginDoneTV.as_view(), name='login_done'),
    path('logout/', logout, name='logout'),
    path('myPage/', MyPage.as_view(), name='myPage'),
    path('register/', signup, name='register'),
    path('register/done/', views.SearchFormView.as_view(), name='register_done'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Django Web Programming{% endblock  %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    {% block extra-style %}{% endblock %}
</head>

<body style="padding-top:90px;">

<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
    <li class="nav-item mx-2 btn btn-primary" style="font-size: 20px"><a class="nav-link text-white" href="{% url 'home' %}">PA8</a></li>
    <li class="nav-item mx-2 btn btn-primary">
      <a class="nav-link text-white" href="{% url 'blog:index' %}">Blog</a>
    </li>
    <ul class="navbar-nav ml-5 mr-5">
        <li class="nav-item dropdown mx-1 btn btn-primary">
            {% if user.is_active %}
            <a class="nav-link dropdown-toggle text-white" href="#" data-bs-toggle="dropdown">
                <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;</a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                <li><a class="dropdown-item" href="{% url 'myPage' %}">My page</a></li>
            </ul>
            {% else %}
            <a class="nav-link dropdown-toggle text-white" href="#" data-bs-toggle="dropdown">
                <i class="fas fa-user"></i>&ensp;익명&ensp;</a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>
                <li><a class="dropdown-item" href="{% url 'register' %}">Register</a></li>
            </ul>
            {% endif %}
        </li>
    </ul>
</nav>

<div class="container">
    {% block content %}{% endblock %}
</div>

{% block footer %}{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/83c045e898.js" crossorigin="anonymous"></script>

{% block extra-script %}{% endblock %}

</body>
</html>

templates/home.html
{% extends "base.html" %}

{% load static %}

{% block title %}home.html{% endblock %}

{% block extra-style %}
<style type="text/css">
  .home-image{
    background-image: url("{% static 'img/lion1.jpg' %}");
    background-repeat: no-repeat;
    background-position: center;
    background-size: 100%;
    height: 500px;
    border-top: 10px solid #ccc;
    border-bottom: 10px solid #ccc;
    padding: 20px 0 0 20px;
  }
  .title {
    color: #c80;
    font-weight: bold;
  }
  .powered {
    position: relative;
    top: 77%;
    color: #cc0;
    font-style: italic;
  }
</style>
{% endblock %}

{% block content %}
    <div class="home-image">
        <h2 class="title">Home</h2>
    </div>
{% endblock content %}

templates/password_change_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}password_change_form.html{% endblock %}

{% block content %}

    <h1>{{ title }}</h1>
    <p class="font-italic">Please enter your old password for security's sake,
    and then enter your new password twice.</p>

    {% if form.errors %}
    <div class="alert alert-danger">
        <div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
        {% form.errors %}
    </div>
    {% endif %}

    <form action="." method="post" class="card pt-3">{% csrf_token %}
        <div class="form-group row">
            {{ form.old_password|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.old_password|add_class:"form-control"|attr:"autofocus" }}
            </div>
        </div>
        <div class="form-group row">
            {{ form.new_password1|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.new_password1|add_class:"form-control" }}
            </div>
        </div>
        <div class="form-group row">
            {{ form.new_password2|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.new_password2|add_class:"form-control" }}
            </div>
        </div>

        <div class="form-group">
            <div class="offset-sm-3 col-sm-5">
                <input type="submit" value="Log in" class="btn btn-info"/>
                <input type="hidden" name="next" value="{{ next }}"/>
            </div>
        </div>

    </form>


{% endblock %}

templates/practice.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <h1>Hello, world!</h1>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>